FROM rocker/r-ver:3.6.3

RUN apt-get update && apt-get install -y \
    sudo \
    gdebi-core \
    pandoc \
    pandoc-citeproc \
    libcairo2-dev \
    libxt-dev \
    xtail \
    wget \
    libpng-dev \
    libxml2-dev \
    libgsl0-dev \
    make \
    libcurl4-openssl-dev \
    libssl-dev \
    zlib1g-dev \
    libgmp3-dev \
    libmpfr-dev \
    libgit2-dev \
    libssh2-1-dev \
    libgdal-dev \
    gdal-bin \
    libgeos-dev \
    libproj-dev \
    libicu-dev \
    libglpk-dev \
    cron \
    docker.io

# Copy renv.lock and install packages
COPY ./renv.lock ./renv.lock
RUN R -e "install.packages('renv')" && \
    R -e "renv::consent(provided = TRUE)" && \
    R -e "renv::restore()"

COPY ./cron_update /etc/cron.d/cron_update
RUN chmod 0644 /etc/cron.d/cron_update
RUN crontab /etc/cron.d/cron_update 
RUN touch /var/log/cron.log 

COPY ./scripts/ /usr/local/src/scripts/
COPY ./utils/ /usr/local/src/utils/

CMD cron && tail -f /var/log/cron.log
