version: '3.1'

services:
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topictool_shiny
    volumes:
      - ./data/:/srv/shiny-server/data/
      - ./global.r:/srv/shiny-server/global.r
      - ./server.r:/srv/shiny-server/server.r
      - ./ui.r:/srv/shiny-server/ui.r
      - ./scripts/:/srv/shiny-server/scripts/
      - ./www/:/srv/shiny-server/www/
      - ./utils/:/srv/shiny-server/utils/
    ports:
      - '3838:3838'
    networks:
      - dash
  updater:
    build:
      context: .
      dockerfile: Dockerfile_R
    container_name: topictool_data_updater
    volumes:
      - ./data/:/usr/local/src/data/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dash

networks:
  dash:
    driver: bridge
    name: dash
